import re
from typing import List, Optional

from app.services.genre_normalizer import normalize_genre


REJECT_EXACT = {
    "female vocalists",
    "male vocalists",
    "seen live",
    "favorites",
    "favourite",
    "favorite",
    "party",
    "aoty",
    "soty",
    "love at first listen",
}

REJECT_PATTERN_LIST = [
    r"^\d{4}$",                    # 2014
    r"^\d{2}s$",                   # 80s, 90s
    r"^\d{4}s$",                   # 2010s
    r"^best of \d{4}$",            # best of 2018
    r"^best of \d{4}s$",           # best of 2010s
    r"^summer \d{4}$",             # summer 2014
]

MAX_TAG_LENGTH = 40

GENRE_KEYWORDS = {
    "pop",
    "chill",
    "lofi",
    "rock",
    "rap",
    "hip hop",
    "hip-hop",
    "r&b",
    "edm",
    "dance",
    "house",
    "trap",
    "ambient",
    "synthpop",
    "synthwave",
    "gospel",
    "ballad",
    "jazz",
    "soul",
    "indie",
    "rnb",
    "alternative",
    "electro",
    "electropop",
    "electro house",
    "dance-pop",
    "pop-soul",
    "quiet storm",
    "new jack swing",
    "drum and bass",
    "dnb",
    "ukg",
    "garage",
    "uk garage",
    "2-step",
    "future garage",
    "grime",
    "dubstep",
    "brostep",
    "chillstep",
    "melodic dubstep",
    "future bass",
    "bass",
    "bass music",
    "trap edm",
    "hardstyle",
    "hardcore",
    "happy hardcore",
    "gabber",
    "techno",
    "minimal techno",
    "melodic techno",
    "deep techno",
    "acid techno",
    "trance",
    "progressive trance",
    "uplifting trance",
    "psytrance",
    "goa trance",
    "hard trance",
    "progressive house",
    "deep house",
    "tropical house",
    "tech house",
    "future house",
    "big room",
    "big room house",
    "funky house",
    "disco house",
    "nu disco",
    "disco",
    "italo disco",
    "boogie",
    "funk",
    "p-funk",
    "neo soul",
    "contemporary r&b",
    "smooth jazz",
    "bebop",
    "hard bop",
    "cool jazz",
    "free jazz",
    "fusion",
    "jazz fusion",
    "latin jazz",
    "swing",
    "big band",
    "blues",
    "delta blues",
    "chicago blues",
    "electric blues",
    "acoustic blues",
    "country",
    "alt-country",
    "country rock",
    "outlaw country",
    "bluegrass",
    "americana",
    "folk",
    "folk rock",
    "indie folk",
    "contemporary folk",
    "celtic",
    "celtic folk",
    "world",
    "world music",
    "afrobeat",
    "afrobeats",
    "afropop",
    "highlife",
    "juju",
    "soukous",
    "makossa",
    "mbalax",
    "latin",
    "latin pop",
    "reggaeton",
    "latin trap",
    "salsa",
    "bachata",
    "merengue",
    "cumbia",
    "vallenato",
    "bossa nova",
    "samba",
    "mpb",
    "tango",
    "flamenco",
    "spanish",
    "k-pop",
    "j-pop",
    "c-pop",
    "mandopop",
    "cantopop",
    "j-rock",
    "k-rock",
    "anime",
    "anisong",
    "vocaloid",
    "city pop",
    "enka",
    "visual kei",
    "industrial",
    "industrial rock",
    "industrial metal",
    "ebm",
    "electronic body music",
    "aggrotech",
    "darkwave",
    "coldwave",
    "post-punk",
    "gothic",
    "goth",
    "goth rock",
    "deathrock",
    "shoegaze",
    "dream pop",
    "ethereal",
    "noise",
    "noise rock",
    "harsh noise",
    "power electronics",
    "experimental",
    "avant-garde",
    "glitch",
    "idm",
    "intelligent dance music",
    "breakcore",
    "drill",
    "uk drill",
    "chicago drill",
    "trap soul",
    "emo rap",
    "cloud rap",
    "phonk",
    "lo-fi",
    "lofi hip hop",
    "chillhop",
    "boom bap",
    "east coast hip hop",
    "west coast hip hop",
    "southern hip hop",
    "gangsta rap",
    "conscious hip hop",
    "alternative hip hop",
    "underground hip hop",
    "hardcore hip hop",
    "trap metal",
    "rage",
    "hyperpop",
    "dancehall",
    "reggae",
    "dub",
    "roots reggae",
    "ska",
    "ska punk",
    "rocksteady",
    "punk",
    "punk rock",
    "hardcore punk",
    "post-hardcore",
    "emo",
    "midwest emo",
    "pop punk",
    "skate punk",
    "crust punk",
    "d-beat",
    "oi",
    "anarcho punk",
    "garage rock",
    "indie rock",
    "alternative rock",
    "britpop",
    "post-britpop",
    "grunge",
    "post-grunge",
    "stoner rock",
    "desert rock",
    "psychedelic rock",
    "acid rock",
    "progressive rock",
    "prog rock",
    "math rock",
    "art rock",
    "noise pop",
    "power pop",
    "soft rock",
    "classic rock",
    "arena rock",
    "heartland rock",
    "hard rock",
    "metal",
    "heavy metal",
    "thrash metal",
    "death metal",
    "black metal",
    "doom metal",
    "sludge metal",
    "metalcore",
    "deathcore",
    "progressive metal",
    "nu metal",
    "groove metal",
    "power metal",
    "symphonic metal",
    "folk metal",
    "viking metal",
    "industrial metal",
    "melodic death metal",
    "post-metal",
    "rap metal",
    "rap rock",
    "christian rock",
    "christian hip hop",
    "worship",
    "praise",
    "classical",
    "baroque",
    "romantic",
    "modern classical",
    "contemporary classical",
    "minimalism",
    "opera",
    "choral",
    "orchestral",
    "soundtrack",
    "film score",
    "video game music",
    "vaporwave",
    "mallsoft",
    "future funk",
    "synth",
    "retrowave",
    "chiptune",
    "8-bit",
    "16-bit",
    "new age",
    "meditation",
    "spa",
    "healing",
    "drone",
    "field recording",
    "spoken word",
    "comedy",
    "children's music",
    "lullaby",
    "holiday",
    "christmas",
    "halloween",
    "party",
    "club",
    "workout",
    "fitness",
    "running",
    "study",
    "focus",
    "sleep",
    "instrumental",
    "acoustic",
    "piano",
    "guitar",
    "covers",
    "remix",
    "bootleg",
    "live",
    "demo",
    "mixtape",
    "freestyle",
    "underground",
    "mainstream",
    "viral",
    "tiktok",
    "bedroom pop",
    "indie pop",
    "alt pop",
    "dark pop",
    "art pop",
    "electronic pop",
    "pop rock",
    "teen pop",
    "kawaii",
    "bubblegum pop",
    "europop",
    "french pop",
    "german pop",
    "italian pop",
    "spanish pop",
    "arabic pop",
    "turkish pop",
    "greek pop",
    "scandinavian pop",
    "norwegian pop",
    "swedish pop",
    "danish pop",
    "finnish pop",
    "icelandic pop",
    "russian pop",
    "uk pop",
    "us pop",
    "australian pop",
    "canadian pop",
    "african pop",
    "brazilian pop",
    "indian pop",
    "bollywood",
    "tollywood",
    "kollywood",
    "desi hip hop",
    "punjabi",
    "bhangra",
    "qawwali",
    "ghazal",
    "traditional",
    "folk traditional",
    "ethnic",
    "tribal",
    "ritual",
    "spiritual",
    "devotional",
    "sufi",
    "chant",
    "mantra",
    "new wave",
    "no wave",
    "sophisti-pop",
    "yacht rock",
    "soft pop",
    "adult contemporary",
    "easy listening",
    "lounge",
    "chillout",
    "downtempo",
    "trip hop",
    "acid jazz",
    "broken beat",
    "future jazz",
    "nu jazz",
    "deep funk",
    "rare groove",
    "motown",
    "northern soul",
    "southern soul",
    "philly soul",
    "blue-eyed soul",
    "psychedelic soul",
    "neo-psychedelia",
    "psychedelic pop",
    "sunshine pop",
    "baroque pop",
    "chamber pop",
    "glam rock",
    "glam metal",
    "hair metal",
    "slowcore",
    "sadcore",
    "lo-fi rock",
    "garage punk",
    "garage pop",
    "surf rock",
    "surf pop",
    "rockabilly",
    "psychobilly",
    "cowpunk",
    "western",
    "film music",
    "epic",
    "cinematic",
    "trailer music",
    "orchestral pop",
    "symphonic rock",
    "symphonic pop",
    "epic music",
    "hybrid orchestral",
    "dark ambient",
    "space ambient",
    "ambient techno",
    "ambient house",
    "chillwave",
    "hypnagogic pop",
    "witch house",
    "seapunk",
    "electroclash",
    "fidget house",
    "jersey club",
    "baltimore club",
    "miami bass",
    "ghetto house",
    "footwork",
    "juke",
    "hard dance",
    "eurodance",
    "hands up",
    "italo dance",
    "progressive breaks",
    "breakbeat",
    "nu breaks",
    "funky breaks",
    "big beat",
    "skweee",
    "wonky",
    "future garage bass",
    "bassline",
    "donk",
    "bounce",
    "new orleans bounce",
    "philly club",
    "latin house",
    "afro house",
    "melodic house",
    "organic house",
    "deep tech",
    "tech trance",
    "psybreaks",
    "psybient",
    "world fusion",
    "global bass",
    "moombahton",
    "moombahcore",
    "tropical bass",
    "zouk",
    "kompa",
    "gqom",
    "amapiano",
    "neo-soul",
    "trip-hop",
    "free-jazz",
    "cool-jazz",
    "hard-bop",
    "big-band",
    "delta-blues",
    "chicago-blues",
    "electric-blues",
    "acoustic-blues",
    "country-rock",
    "outlaw-country",
    "folk-rock",
    "indie-folk",
    "contemporary-folk",
    "celtic-folk",
    "latin-pop",
    "latin-trap",
    "bossa-nova",
    "city-pop",
    "industrial-rock",
    "industrial-metal",
    "electronic-body-music",
    "goth-rock",
    "dream-pop",
    "trap-soul",
    "emo-rap",
    "cloud-rap",
    "punk-rock",
    "hardcore-punk",
    "garage-rock",
    "indie-rock",
    "alternative-rock",
    "psychedelic-rock",
    "progressive-rock",
    "math-rock",
    "hard-rock",
    "heavy-metal",
    "thrash-metal",
    "death-metal",
    "black-metal",
    "progressive-metal",
    "nu-metal",
    "power-metal",
    "symphonic-metal",
    "film-score",
    "future-funk",
    "new-age",
    "indie-pop",
    "dark-pop",
    "art-pop",
    "teen-pop",
    "bubblegum-pop",
    "adult-contemporary",
    "easy-listening",
    "acid-jazz",
    "future-jazz",
    "blue-eyed-soul",
    "baroque-pop",
    "glam-rock",
    "glam-metal",
    "post-rock",
    "lo-fi-rock",
    "surf-rock",
    "surf-pop",
    "film-music",
    "epic-music",
    "dark-ambient",
    "space-ambient",
    "ambient-techno",
    "ambient-house",
    "hard-dance",
    "eurodance",
    "big-beat",
    "afro-house",
    "melodic-house",
    "world-fusion",
    "tropical-bass",
    "roots",
    "roots music",
    "roots rock",
    "folk-pop",
    "acoustic folk",
    "acoustic pop",
    "acoustic rock",
    "soul jazz",
    "jazz-pop",
    "jazz pop",
    "alt rock",
    "alt-rock",
    "reggae-pop",
    "reggae pop",
    "surf",
    "didgeridoo",
    "roots-reggae",
    "melodic-house-and-techno",
    "organic-electronic",
    "electronic",
    "alternative-pop",
    "alternative pop",
    "soft-pop",
    "orchestral-pop",
    "dance pop",
    "pop soul",
    "quiet-storm",
    "new-jack-swing",
    "electro-house",
    "drum-and-bass",
    "d&b",
    "uk-garage",
    "future-garage",
    "melodic-dubstep",
    "future-bass",
    "bass-music",
    "trap-edm",
    "happy-hardcore",
    "minimal-techno",
    "melodic-techno",
    "deep-techno",
    "acid-techno",
    "progressive-trance",
    "uplifting-trance",
    "goa-trance",
    "hard-trance",
    "progressive-house",
    "deep-house",
    "tropical-house",
    "tech-house",
    "future-house",
    "big-room",
    "big-room-house",
    "funky-house",
    "disco-house",
    "nu-disco",
    "italo-disco",
    "contemporary-r&b",
    "smooth-jazz",
    "jazz-fusion",
    "latin-jazz",
    "intelligent-dance-music",
    "lofi-hip-hop",
    "east-coast-hip-hop",
    "west-coast-hip-hop",
    "southern-hip-hop",
    "gangsta-rap",
    "conscious-hip-hop",
    "alternative-hip-hop",
    "underground-hip-hop",
    "hardcore-hip-hop",
    "euro Pop",
    "euro-Pop"
}


def _looks_like_genre(normalized: str) -> bool:
    lowered = normalized.casefold()
    return lowered in GENRE_KEYWORDS


def clean_lastfm_genre_tags(
    raw_tags: List[str],
    artist_names: Optional[List[str]] = None,
    track_title: Optional[str] = None,
    album_title: Optional[str] = None,
) -> List[str]:
    cleaned: List[str] = []
    seen = set()

    normalized_artist_names = {
        (artist_name or "").strip().casefold()
        for artist_name in (artist_names or [])
        if (artist_name or "").strip()
    }

    normalized_track_title = (track_title or "").strip().casefold()
    normalized_album_title = (album_title or "").strip().casefold()

    for raw_tag in raw_tags:
        if not raw_tag:
            continue

        tag = raw_tag.strip()
        if not tag:
            continue

        lowered = tag.casefold()

        if lowered in normalized_artist_names:
            continue

        if normalized_track_title and lowered == normalized_track_title:
            continue

        if normalized_album_title and lowered == normalized_album_title:
            continue

        if lowered in REJECT_EXACT:
            continue

        if len(tag) > MAX_TAG_LENGTH:
            continue

        should_reject = False
        for pattern in REJECT_PATTERN_LIST:
            if re.match(pattern, lowered):
                should_reject = True
                break

        if should_reject:
            continue

        normalized = normalize_genre(tag)

        if not normalized:
            continue

        normalized_lower = normalized.casefold()

        if normalized_lower in normalized_artist_names:
            continue

        if normalized_track_title and normalized_lower == normalized_track_title:
            continue

        if normalized_album_title and normalized_lower == normalized_album_title:
            continue

        if not _looks_like_genre(normalized):
            continue

        if normalized_lower in seen:
            continue

        seen.add(normalized_lower)
        cleaned.append(normalized)

    return cleaned